### PR TITLE
Bootstrapping zinc bundles from the main app bundle.

### PR DESCRIPTION
**Pull request by amrox**
How it works:
- In your app source, create a directory with the name of the bundle and include all the files inside of it for example:

```
$SRCROOT/
   Resources/
       com.mindsnacks.demo1.sphalerites/
             sphalerite.jpg
             sphalerite@2x.jpg
```
- Add all the files from the bundle into your project, _excluding the parent bundle-name dir_, for example:
  Resources dir
- Add a Run Script phase for the zinc manifest generation script, for example:
  Run script phase
- Instead of just calling:
  `- (void) beginTrackingBundleWithId:(NSString *)bundleId distribution:(NSString *)distro`
  You call:
  `- (void) beginTrackingBundleWithId:(NSString *)bundleId distribution:(NSString *)distro shouldBootstrapFromMainBundle:(BOOL)shouldBootstrap;`
  
  With a path to a manifest file inside the main application bundle.
- During bundle clone, it will check if that bundle_id/version is available locally (in the main bundle). If so, it hard links the SHA-based objects in the zinc dir directly to the files in the main bundle.
- The rest of bundle clone proceeds as normal.

### CODE REVIEW

**Comment by NachoSoto** [comment]
The interface sounds great, but I have one question: what would be the process to create this local manifest? I'm wondering how cumbersome it is to create, and add/update files.

As for your question: I think the method is really straightforward.

**Comment by JaviSoto** [comment]
I think the interface through which you specify that you have some stuff that is local is perfect: telling Zinc what the path for the manifest is is the simplest way after all :)
My only concern as a user of this library would be: what happens if I update those files on the remote repository? Will Zinc stop pointing to my local version?

**Comment by amrox** [comment]
One way to get the manifest would be to just pull them from the zinc catalog. The command could be something like:

`zinc bundle:clone --source http://m.com/ --bundle com.m.test1 --distro master`

Another way is to just write the manifest by hand. However, this is a little cumbersome since you have to keep the SHA in the manifest matching the actual SHA of the file. 

Finally, it could _generate_ the local manifest, given a list of files and a bundle id. This is probably the friendliest. My only hesitation is introducing another noun ("local bundle list" or something) into the zinc vocabulary.

I do suspect it's important to pre-calculate the SHAs. It seems expensive to calculate them all on the fly, though I haven't actually measured it.

**Comment by amrox** [comment]
### option 1 - local bundles are the same as remote bundles

This means that a real manifest from a real zinc catalog is included inside. The process for updating files inside an app becomes:
- upload a new bundle to the zinc catalog `zinc bundle:update`
- then re-clone the bundle locally to get the manifest `zinc bundle:clone`

While this is more correct, it's kind of a pain for the developer. You can't just drag new files into the project and build & run.

### option 2 - local bundles are un-versioned

This is nice because you don't need to interact with a zinc catalog to generate your Manifest (or Manifest-ish). You can just have a list of files, and everything else can be generated as build steps.

However, this has some implications.
- If the bundle is version-less (essentially version 0), _any_ remote bundle will overwrite it, because bundle versioning in catalogs starts at 1. So even if the local files are "newer" they'll get overwritten by the remote files
- Even if we don't have remote bundles (which defeats the purpose of zinc but whatever), we still have a problem updating local files. Through app updates we could have a _different_ version 0, meaning we would have to ensure that any locally cloned bundles are still valid at app startup (not app resume).

---

Thoughts?

**Comment by JaviSoto** [comment]
I would say option 2 is the way to go, but I may not be aware of all the consequences.

I think _the local files will get overwritten by the remote files_ is actually the expected behaviour: you ship with some initial state, but if you want the user to see updated content, you store that in Zinc, and the app downloads that and uses it over the initial bundle content.

**Comment by NachoSoto** [comment]
Sorry for the late response, here are my thoughts:

When I asked about the workflow for including those local files in the app, this is exactly what I meant, and option 2 is exactly how I was picturing it. I think neither of those two implications are a real problem, but instead a good thing:
- Makes sense that the local files in the app are always "outdated" from day 0, that allows us to fix for any mistakes we might make in those files when shipping the app.
- This would be the same behavior as before, wouldn't it?

**Comment by amrox** [comment]
### First take a manifest generation solution.

First, you need to create a local file list, which looks like this:

```
{
    "bundle": "com.mindsnacks.demo1.sphalerites",
    "files": [
        "sphalerite.jpg",
        "sphalerite@2x.jpg"]
}
```

Then as a build step, use the `generate_manifest_from_local_file_list.py` script

Build phase

---

Files in project

Pros:
- local file list more simple to deal with then the full manifest.
- manifest is generated automatically

Cons:
- difference between local file list and manifest might be confusing?
- possible have to add many build steps if many bundles need to be bootstrap

Thoughts?

**Comment by NachoSoto** [comment]
We need a way to specify what files are part of a bundle and which are not. Also managing a list with a simple syntax makes it much easier to update than changing the manifest, so I think having two different files is not a big deal. Would there be a way to generate all the bundles out of all the local file lists with just one build step? Adding all the lists as input files or something?

**Comment by amrox** [comment]
### Second take a manifest generation solution.

I modified the generation script to scan a directory. The name of the directory is assumed to be the name of the bundle. The Run Script phase now looks like this:

Run script phase

Multiple arguments could can be added, but right now it's manual. I'm still looking for a better solution.

However, this does clean up the Resources. No more local file list or extra manifest reference. The resources just contain the files:

Resources

Also, the API for opting into bootstrapping got a little simpler.

Old:

```
NSString* bootstrapManifestPath = [[NSBundle mainBundle] pathForResource:@"com.mindsnacks.demo1.sphalerites" ofType:@"json"];
[repo beginTrackingBundleWithId:@"com.mindsnacks.demo1.sphalerites" distribution:@"master" localManifestPath:bootstrapManifestPath];
```

New:

```
[repo beginTrackingBundleWithId:@"com.mindsnacks.demo1.sphalerites" distribution:@"master" shouldBootstrapFromMainBundle:YES];
```

**Comment by amrox** [comment]
I think the Run script phase is improved with the new "Xcode mode". Feeling good about the feature.

Run script phase

**Comment by amrox** [comment]
Going to update the main summary and remove the WIP tag

**Comment by NachoSoto** [comment]
:shipit:

**Comment by psql** [comment]
nerds!!!!!!

**Comment by amrox** [comment]
Quite.

**Pull request merged**
